# Generated by Django 2.2.2 on 2019-08-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0002_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.CharField(blank=True, default='https://www.materialui.co/materialIcons/social/person_grey_192x192.png', max_length=255),
        ),
    ]
