# Generated by Django 2.2.2 on 2019-08-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0003_auto_20190803_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
