# Generated by Django 2.2.2 on 2019-06-22 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('username', models.TextField(unique=True)),
                ('password_hash', models.TextField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('birthday', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('bookable', models.BooleanField(default=False)),
                ('host_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='booking.User')),
            ],
        ),
    ]
