# Generated by Django 2.2.2 on 2019-06-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('username', models.TextField(unique=True)),
                ('password_hash', models.TextField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('birthday', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
