# Generated by Django 2.2.2 on 2019-06-29 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_bookingtable_propertyfavourites_propertyownership_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyownership',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='propertyownership',
            name='property',
        ),
        migrations.DeleteModel(
            name='PropertyFavourites',
        ),
        migrations.DeleteModel(
            name='PropertyOwnership',
        ),
    ]
