# Generated by Django 2.2.2 on 2019-06-24 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20190624_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='host_id',
        ),
    ]
