# Generated by Django 2.2.2 on 2019-07-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20190706_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='host_id',
        ),
    ]
