# Generated by Django 2.2.2 on 2019-07-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_property_host_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='num_guests',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
