# Generated by Django 2.2.2 on 2019-06-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20190625_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='host_id',
        ),
        migrations.AlterField(
            model_name='propertyreviews',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userreviews',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
