# Generated by Django 2.2.2 on 2019-07-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20190710_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='num_rooms',
            field=models.IntegerField(default=1),
        ),
    ]
