# Generated by Django 2.2.2 on 2019-07-16 04:31

from django.db import migrations, models
import django.db.models.deletion

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Amenity = apps.get_model("booking", "Amenity")
    db_alias = schema_editor.connection.alias
    Amenity.objects.using(db_alias).bulk_create([
        Amenity(amenity_name="Kitchen"),
        Amenity(amenity_name="Heating"),
        Amenity(amenity_name="Washing machine"),
        Amenity(amenity_name="Wi-Fi"),
        Amenity(amenity_name="Indoor fireplace"),
        Amenity(amenity_name="Iron"),
        Amenity(amenity_name="Laptop friendly workspace"),
        Amenity(amenity_name="Cot"),
        Amenity(amenity_name="Self check-in"),
        Amenity(amenity_name="Shampoo"),
        Amenity(amenity_name="Air conditioning"),
        Amenity(amenity_name="Dryer"),
        Amenity(amenity_name="Breakfast"),
        Amenity(amenity_name="Hangers"),
        Amenity(amenity_name="Hair dryer"),
        Amenity(amenity_name="TV"),
        Amenity(amenity_name="High chair"),
        Amenity(amenity_name="Smoke detector"),
        Amenity(amenity_name="Private bathroom"),
    ])

def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    Amenity = apps.get_model("booking", "Amenity")
    db_alias = schema_editor.connection.alias
    Amenity.objects.using(db_alias).filter(amenity_name="Wifi").delete()
    Amenity.objects.using(db_alias).filter(amenity_name="Kitchen").delete()
    Amenity.objects.using(db_alias).filter(amenity_name="Heating").delete()
    Amenity.objects.using(db_alias).filter(amenity_name="Washing machine").delete()
    Amenity.objects.using(db_alias).filter(amenity_name="Wi-Fi").delete()
    Amenity.objects.using(db_alias).filter(amenity_name="Indoor fireplace").delete()
    Amenity.objects.using(db_alias).filter(amenity_name="Iron").delete()
    Amenity.objects.using(db_alias).filter(amenity_name="Laptop friendly workspace").delete()
    Amenity.objects.using(db_alias).filter(amenity_name="Cot").delete()
    Amenity.objects.using(db_alias).filter(amenity_name="Self check-in").delete()
    Amenity.objects.using(db_alias).filter(amenity_name="Shampoo").delete()
    Amenity.objects.using(db_alias).filter(amenity_name="Air conditioning").delete()
    Amenity.objects.using(db_alias).filter(amenity_name="Dryer").delete()
    Amenity.objects.using(db_alias).filter(amenity_name="Breakfast").delete()
    Amenity.objects.using(db_alias).filter(amenity_name="Hangers").delete()
    Amenity.objects.using(db_alias).filter(amenity_name="Hair dryer").delete()
    Amenity.objects.using(db_alias).filter(amenity_name="TV").delete()
    Amenity.objects.using(db_alias).filter(amenity_name="High chair").delete()
    Amenity.objects.using(db_alias).filter(amenity_name="Smoke detector").delete()
    Amenity.objects.using(db_alias).filter(amenity_name="Private bathroom").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_booking_num_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('amenity_id', models.AutoField(primary_key=True, serialize=False)),
                ('amenity_name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='size',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='PropertyAmenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Amenity')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Property')),
            ],
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
