# Generated by Django 2.2.2 on 2019-07-16 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_booking_num_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('amenity_id', models.AutoField(primary_key=True, serialize=False)),
                ('amenity_name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='size',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='PropertyAmenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Amenities')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Property')),
            ],
        ),
    ]
