# Generated by Django 2.2.2 on 2019-07-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20190716_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='bookable',
        ),
        migrations.AddField(
            model_name='property',
            name='shareable',
            field=models.BooleanField(default=True),
        ),
    ]
