# Generated by Django 2.2.2 on 2019-08-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_bookable'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.TextField(default='Accepted'),
        ),
    ]
