# Generated by Django 2.2.2 on 2019-08-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.TextField(default='Pending'),
        ),
    ]
